services:
  mysql:
    image: mysql:8.0
    container_name: keymasters-db
    restart: unless-stopped
    env_file: .env.db
    environment:
      MYSQL_DATABASE: keymasters
    ports:
      - "3306:3306"
    volumes:
      - .mysql_data:/var/lib/mysql
      - ./scripts-sql:/docker-entrypoint-initdb.d
    command: 
      - --init-file=/docker-entrypoint-initdb.d/00-init.sql
